-- 오류 틀렸습니다
-- GROUP BY 를 하고 나면 DATETIME ATTRIBUTE 가 사라지고
-- HOUR(DATETIME) 자체가 된다
-- 따라서 HAVING 에서 HOUR() 을 적용할 DATETIME을 찾을 수 없게된다
SELECT HOUR( DATETIME ) AS HOUR , COUNT( HOUR(DATETIME) )
FROM ANIMAL_OUTS 
GROUP BY HOUR(DATETIME)
 HAVING HOUR(DATETIME) >=9 
    AND HOUR(DATETIME) <20;

-- AS가 적용 되는것은 제일 먼저 적용되어 SELECT에 바꾸어 줬다면 아래도 그렇게 적용된다
-- 단 SELECT 에서는 그대로 DATETIME 을 써야함
SELECT HOUR(DATETIME) AS HOUR , COUNT( HOUR(DATETIME) ) AS COUNT
FROM ANIMAL_OUTS 
GROUP BY HOUR
 HAVING HOUR >=9 
 AND HOUR<20
 ORDER BY HOUR    

    
    