-- 방법1. IFNULL(NULL이아니면, NULL이면)
SELECT ANIMAL_TYPE, IFNULL(NAME,'No name'),SEX_UPON_INTAKE
FROM ANIMAL_INS 
ORDER BY ANIMAL_ID;
-- 방법2. IF ( 조건, 참이면, 거짓이면)
SELECT ANIMAL_TYPE, IF(NAME IS NULL,'No name',NAME),SEX_UPON_INTAKE
FROM ANIMAL_INS 
ORDER BY ANIMAL_ID;