-- INTACK:손대지 않은 
-- SPAYED FEMALE  중성여성
-- NEUTERED MALE 중성 남성

SELECT ANIMAL_OUTS.ANIMAL_ID,ANIMAL_OUTS.ANIMAL_TYPE,ANIMAL_OUTS.NAME	
FROM ANIMAL_OUTS,ANIMAL_INS
WHERE (ANIMAL_OUTS.ANIMAL_ID=ANIMAL_INS.ANIMAL_ID
        AND ANIMAL_INS.SEX_UPON_INTAKE LIKE '%Intact%'
        AND (ANIMAL_OUTS.SEX_UPON_OUTCOME LIKE '%Spayed%'
            OR ANIMAL_OUTS.SEX_UPON_OUTCOME LIKE '%Neutered%'))
ORDER BY ANIMAL_OUTS.ANIMAL_ID