-- 코드를 입력하세요
WITH RECURSIVE TIME AS (
  (SELECT 0 AS H)
  UNION ALL
  (SELECT H+1 
  FROM TIME
  WHERE H<23)
)

SELECT TIME.H,COUNT(HOUR(ANIMAL_OUTS.DATETIME))
FROM TIME
LEFT OUTER JOIN ANIMAL_OUTS 
ON TIME.H=HOUR(ANIMAL_OUTS.DATETIME)
GROUP BY TIME.H

 